version: '2'
services:
  ripe:
    image: ripe
    build:
      context: .
    command: -c postgres://ripe:ripe@db:5432/ripe
    links:
      - db

  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: ripe
      POSTGRES_USER: ripe
      POSTGRES_PASSWORD: ripe
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local

