version: "3.8"

services:
  irrator:
    image: irrator
    build:
      context: parser
    command: python /app/parse.py -c postgresql://irrator:irrator@postgres:5432/irrator
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: irrator
      POSTGRES_USER: irrator
      POSTGRES_PASSWORD: irrator
    volumes:
      - pg_data:/var/lib/postgresql/data
    hostname: postgres
    ports:
      - "35602:5432"

volumes:
  pg_data:
    driver: local
